version: "3.9"

services:
  postgres:
    container_name: postgres_testing
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5433:5432"

  php-fpm:
    container_name: php-fpm_testing
    build:
      context: ./php-fpm
    volumes:
      - ./../:/var/www
    ports:
      - "3001:3000"

  nginx:
    container_name: nginx_testing
    build:
      context: ./nginx
    volumes:
      - ./../:/var/www
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/environment/local/sites/:/etc/nginx/sites-available
      - ./nginx/environment/local/conf.d/:/etc/nginx/conf.d
    # - ./logs:/var/log
    depends_on:
      - php-fpm
    ports:
      - "81:80"
